#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then change the shebang line above to use that shell, so the
#       script will run with that shell.
#
#   (2) The slurp flag should always be used to capture command output.
#
##############################################################################

set -e

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for daisy-chained symlinks.
while test -L "$PRG"; do
      ls_result=$(ls -ld "$PRG")
      link=$(expr "$ls_result" : '.*-> \(.*\)$')
      case $link in
      /*)
         PRG="$link" ;;
      *)
         PRG=$(dirname "$PRG")"/$link" ;;
      esac
done
SAVED="$(cd "$(dirname "$PRG")" >/dev/null 2>&1 && pwd)"
cd "$SAVED" || exit

APP_HOME=$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)

# Find java.exe
if command -v java >/dev/null 2>&1 ; then
    IS_CYGWIN=false
    IS_MINGW=false
    IS_MSYS=false
fi

# Determine the Java command to use to start the JVM.
if [ ! -z "$JAVA_HOME" ] ; then
    JAVA_HOME=$( (unset JAVA_HOME; command -v java >/dev/null 2>&1 && java -XshowSettings:properties -version 2>/dev/null | grep 'java.home' | cut -d "=" -f 2 | tr -d " ") )
fi

if [ -z "$JAVA_HOME" ] ; then
     javaExecutable="$(which javac)"
     [ -z "$javaExecutable" ] && javaExecutable="$(which java)"
     if [ ! -z "$javaExecutable" ] && ! [ "`expr \"$javaExecutable\" : '\([^ ]*\)'`" = "no" ]; then
          javaHome="`dirname \"$javaExecutable\"`"
          javaHome=`expr "$javaHome" : '\(.*\)/bin/?$'` || true
          JAVA_HOME="$javaHome"
          export JAVA_HOME
     fi
fi

if [ -z "$JAVACMD" ] ; then
     if [ ! -z "$JAVA_HOME"  ] ; then
          JAVACMD="$JAVA_HOME/bin/java"
     else
          JAVACMD="$(which java)"
     fi
fi

if [ ! -x "$JAVACMD" ] ; then
     echo "Error: JAVA_HOME is not defined correctly." >&2
     echo "  We cannot execute java in \"$JAVA_HOME/bin/java\"" >&2
     exit 1
fi

if [ -z "$JAVA_HOME" ] ; then
     echo "Warning: JAVA_HOME environment variable is not set."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
     MAX_FD_LIMIT=$(ulimit -H -n)
     if [ $? -eq 0 ] ; then
          if [ "$MAX_FD_LIMIT" != "unlimited" ] ; then
               ulimit -n $MAX_FD_LIMIT
          fi
     fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...libdir is not defined yet...
#   * the application home directory from which to find libs

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
     JAVA="$JAVA_HOME/bin/java"
else
     JAVA="java"
fi

exec "$JAVA" \
     -Dorg.gradle.appname="$APP_BASE_NAME" \
     -classpath "$CLASSPATH" \
     org.gradle.wrapper.GradleWrapperMain \
     "$@"
